### ISSUE TITLE
UnicodeError nell'invio delle email da server beFair2

### ISSUE THREAD

**Issue by feroda** [befair/gasistafelice#131]
`cat /var/www/gf_desmc_prod/gasistafelice/gf.log.unicodeerror`

```
ERROR Internal Server Error: /gasistafelice/rest/order/12618/order_report/emailmepdf
  Traceback (most recent call last):
    File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
      response = callback(request, *callback_args, **callback_kwargs)
    File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
      return view_func(request, *args, **kwargs)
    File "./rest/views/__init__.py", line 246, in view_factory
      response = handler.get_response(request, resource_type, resource_id, args)
    File "./rest/views/blocks/order_report.py", line 209, in get_response
      rv = self._send_email_logged()
    File "./rest/views/blocks/order_report.py", line 236, in _send_email_logged
      self.resource.send_email([to],None, 'Order Email me', self.request.user)
    File "/var/www/gf_desmc_prod/gasistafelice/gas/models/order.py", line 992, in send_email
      message += more_info
  TypeError: coercing to Unicode: need string or buffer, User found
```

**Comment by feroda** [comment]
FIXED in produzione dato che era una modifica al volo non committata nel codice dovuta all'introduzione del parametro "bcc" nel metodo send_email dell'order.

Il problema di mancato delivery delle email risiede sempre nella reputazione del server
