### ISSUE TITLE
Eliminazione utente non funziona

### ISSUE THREAD

**Issue by feroda** [befair/gasistafelice#215]
Dominique riporta:

> non riesco a cancellare questo utente http://ordini.desmacerata.it/gasistafelice/admin/auth/user/299/delete/ che dicono i log?

**Comment by feroda** [comment]
l'errore avviene nella gestione del segnale di variazione del ruolo di default quando un ruolo viene cancellato. Se l'eliminazione del ruolo (ppr) avviene a seguito dell'eliminazione dell'utente, quando l'handler cerca di resettare il ruolo di default per gli utenti collegati a quel ppr, non lo/li trova e pertanto va in errore.

È sicuro mettere un try/except qui e vado a farlo.

I log dicono:

```
ERROR Internal Server Error: /gasistafelice/admin/auth/user/299/delete/
Traceback (most recent call last):
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 307, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/utils/decorators.py", line 93, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 79, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 197, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/utils/decorators.py", line 28, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/utils/decorators.py", line 93, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/utils/decorators.py", line 24, in bound_func
    return func(self, *args2, **kwargs2)
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/db/transaction.py", line 217, in inner
    res = func(*args, **kwargs)
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1208, in delete_view
    self.delete_model(request, obj)
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 671, in delete_model
    obj.delete()
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/db/models/base.py", line 581, in delete
    collector.delete()
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 63, in decorated
    func(self, *args, **kwargs)
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 260, in delete
    sender=model, instance=obj, using=self.using
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/www/gf_desmc_prod/gasistafelice/users/models.py", line 86, in on_ppr_delete_reset_default_role
    p = deleted_ppr.principal #Principal can be a User or a Group
  File "/usr/local/venvs/gf_desmc_orig/src/django-flexi-auth/flexi_auth/models.py", line 347, in get_principal
    return self.user or self.group
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 315, in __get__
    rel_obj = QuerySet(self.field.rel.to).using(db).get(**params)
  File "/usr/local/venvs/gf_desmc_orig/local/lib/python2.7/site-packages/django/db/models/query.py", line 349, in get
    % self.model._meta.object_name)
DoesNotExist: User matching query does not exist.
```
